name: Build and deploy Node.js app to Azure Web App - matricula-app-27749

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: echo "Sem etapa de build para este app."

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'matricula-app-27749'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
